apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-secrets
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: homepage-secrets
    creationPolicy: Owner
  data:
    - secretKey: HOMEPAGE_VAR_ADGUARD_PASSWORD
      remoteRef:
        key: secret/homepage
        property: adguard-password
    - secretKey: HOMEPAGE_VAR_ARGOCD_TOKEN
      remoteRef:
        key: secret/homepage
        property: argocd-token
    - secretKey: HOMEPAGE_VAR_BAZARR_API_KEY
      remoteRef:
        key: secret/homepage
        property: bazarr-api-key
    - secretKey: HOMEPAGE_VAR_GRAFANA_PASSWORD
      remoteRef:
        key: secret/homepage
        property: grafana-password
    - secretKey: HOMEPAGE_VAR_JELLYFIN_API_KEY
      remoteRef:
        key: secret/homepage
        property: jellyfin-api-key
    - secretKey: HOMEPAGE_VAR_JELLYSEERR_API_KEY
      remoteRef:
        key: secret/homepage
        property: jellyseerr-api-key
    - secretKey: HOMEPAGE_VAR_RADARR_API_KEY
      remoteRef:
        key: secret/homepage
        property: radarr-api-key
    - secretKey: HOMEPAGE_VAR_SABNZBD_API_KEY
      remoteRef:
        key: secret/homepage
        property: sabnzbd-api-key
    - secretKey: HOMEPAGE_VAR_SONARR_API_KEY
      remoteRef:
        key: secret/homepage
        property: sonarr-api-key
