apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-dashboard
  namespace: longhorn-system
spec:
  entryPoints: [websecure]
  routes:
  - match: Host(`longhorn.woitzik.dev`)
    kind: Rule
    middlewares: [{name: authelia, namespace: apps}]
    services: [{name: longhorn-frontend, port: 80}]
  tls: {secretName: wildcard-woitzik-dev-tls}
