---
ansible_python_interpreter: /usr/bin/python3
upgrade_packages: true

common_packages:
  - curl
  - vim
  - git
  - htop
  - net-tools
  - bridge-utils
  - dnsutils
  - gnupg
  - ca-certificates

monitoring_core_host: "loki.woitzik.dev" # Was 10.0.20.252, but Loki is now in k3s. Requires an Ingress or LoadBalancer to be set up.
loki_push_url: "https://loki.woitzik.dev/loki/api/v1/push"
