---
ansible_python_interpreter: /usr/bin/python3
upgrade_packages: true

common_packages:
  - curl
  - vim
  - git
  - htop
  - net-tools
  - bridge-utils
  - dnsutils
  - gnupg
  - ca-certificates

monitoring_core_host: "10.0.20.252"
