apiVersion: v1
kind: Service
metadata:
  name: external-pve
  namespace: apps
spec:
  ports:
  - name: https
    port: 8006
    targetPort: 8006
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-pve
  namespace: apps
subsets:
- addresses:
  - ip: 10.0.10.10
  ports:
  - name: https
    port: 8006
---
apiVersion: v1
kind: Service
metadata:
  name: external-pbs
  namespace: apps
spec:
  ports:
  - name: https
    port: 8007
    targetPort: 8007
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-pbs
  namespace: apps
subsets:
- addresses:
  - ip: 10.0.10.110
  ports:
  - name: https
    port: 8007
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: infrastructure-pve
  namespace: apps
spec:
  entryPoints: [websecure]
  routes:
  - match: Host(`pve.woitzik.dev`)
    kind: Rule
    services:
    - name: external-pve
      port: 8006
      scheme: https
      serversTransport: insecure-transport
  tls: {secretName: wildcard-woitzik-dev-tls}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: infrastructure-pbs
  namespace: apps
spec:
  entryPoints: [websecure]
  routes:
  - match: Host(`backup.woitzik.dev`)
    kind: Rule
    services:
    - name: external-pbs
      port: 8007
      scheme: https
      serversTransport: insecure-transport
  tls: {secretName: wildcard-woitzik-dev-tls}
