apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pve
  namespace: kube-system
spec:
  entryPoints: [websecure]
  routes:
  - match: Host(`pve.woitzik.dev`)
    kind: Rule
    services:
    - name: external-pve
      port: 8006
      scheme: https
      serversTransport: insecure-transport
  tls: {secretName: wildcard-woitzik-dev-tls}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: backup
  namespace: kube-system
spec:
  entryPoints: [websecure]
  routes:
  - match: Host(`backup.woitzik.dev`)
    kind: Rule
    services:
    - name: external-pbs
      port: 8007
      scheme: https
      serversTransport: insecure-transport
  tls: {secretName: wildcard-woitzik-dev-tls}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: kube-system
spec:
  entryPoints: [websecure, traefik]
  routes:
  - match: Host(`traefik.woitzik.dev`)
    kind: Rule
    middlewares: [{name: authelia, namespace: apps}]
    services: [{name: api@internal, kind: TraefikService}]
  tls: {secretName: wildcard-woitzik-dev-tls}
