apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 61.3.2
    chart: kube-prometheus-stack
    helm:
      values: |
        prometheusOperator:
          crds:
            enabled: false
        grafana:
          enabled: true
          ingress:
            enabled: false
          adminPassword: "homelab-admin-2026"
          sidecar:
            datasources:
              enabled: true
          grafana.ini:
            auth:
              oauth_auto_login: true
            server:
              domain: monitoring.woitzik.dev
              root_url: https://monitoring.woitzik.dev
              serve_from_sub_path: false
            auth.generic_oauth:
              enabled: true
              name: Authelia
              icon: signin
              client_id: grafana
              client_secret: dubist1plebyakalb
              scopes: openid profile email groups
              empty_scopes: false
              auth_url: https://auth.woitzik.dev/api/oidc/authorization
              token_url: https://auth.woitzik.dev/api/oidc/token
              api_url: https://auth.woitzik.dev/api/oidc/userinfo
              login_attribute_path: preferred_username
              groups_attribute_path: groups
              role_attribute_path: contains(groups[*], 'admins') && 'Admin' || 'Viewer'
            security:
              allow_embedding: true
              cookie_samesite: lax
              cookie_secure: false
            sessions:
              cookie_samesite: lax
              cookie_secure: false
        prometheus:
          prometheusSpec:
            retention: 30d
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: longhorn
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 20Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
