apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.6.2
    chart: loki
    helm:
      values: |
        loki:
          analytics:
            reporting_enabled: false
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          compactor:
            working_directory: /var/loki/compactor
            compaction_interval: 10m
            retention_enabled: true
            retention_delete_delay: 2h
            retention_delete_worker_count: 150
            delete_request_store: s3
          limits_config:
            retention_period: 30d
          ruler:
            alertmanager_url: http://kube-prometheus-stack-alertmanager.monitoring.svc.cluster.local:9093
            enable_api: true
            ring:
              kvstore:
                store: memberlist
            rule_path: /var/loki/rules
            storage:
              type: s3
              s3:
                bucketnames: loki-data
                endpoint: http://minio.apps.svc.cluster.local:9000
                region: main
                s3_force_path_style: true
                insecure: true
          memberlist:
            join_members:
              - loki-memberlist.monitoring.svc.cluster.local
          storage:
            type: s3
            bucketNames:
              chunks: loki-data
              ruler: loki-data
              admin: loki-data
            s3:
              endpoint: http://minio.apps.svc.cluster.local:9000
              region: main
              s3ForcePathStyle: true
              insecure: true
          schemaConfig:
            configs:
              - from: "2024-04-01"
                object_store: s3
                store: tsdb
                schema: v13
                index:
                  prefix: index_
                  period: 24h
        deploymentMode: SingleBinary
        singleBinary:
          replicas: 1
          extraEnv:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: loki-s3-secrets
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-s3-secrets
                  key: secret-access-key
        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0
        chunksCache:
          allocatedMemory: 512
          maxItemSize: 5m
        resultsCache:
          allocatedMemory: 512
        lokiCanary:
          enabled: false
        test:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.16.4
    chart: promtail
    helm:
      values: |
        config:
          clients:
            - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
