apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-s3-secrets
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: loki-s3-secrets
    creationPolicy: Merge
  data:
    - secretKey: access-key-id
      remoteRef:
        key: secret/garage
        property: loki-access-key-id
    - secretKey: secret-access-key
      remoteRef:
        key: secret/garage
        property: loki-secret-access-key
