apiVersion: v1
kind: Secret
metadata:
  name: cnpg-garage-backup
  namespace: database
type: Opaque
stringData:
  access-key-id: GKf5de79528ade5ffced70bd20
  secret-access-key: 1b5bd8fa6bbe0a9a8f360368256b8be9800fcc8b297425caad89c828bf4731a4
