apiVersion: v1
kind: Service
metadata:
  name: postgres-authelia
  namespace: database
spec:
  ports:
  - port: 5432
  selector:
    app: postgres-authelia
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-authelia
  namespace: database
spec:
  serviceName: "postgres-authelia"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-authelia
  template:
    metadata:
      labels:
        app: postgres-authelia
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: postgresql
        image: public.ecr.aws/bitnami/postgresql:16
        env:
        - name: POSTGRESQL_USERNAME
          value: "authelia"
        - name: POSTGRESQL_DATABASE
          value: "authelia"
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRESQL_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /bitnami/postgresql
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 8Gi
