apiVersion: v1
kind: Secret
metadata:
  name: kasm-secrets
  namespace: apps
type: Opaque
stringData:
  db-password: "kasm-db-pass-change-me"
  user-password: "kasm-user-pass-change-me"
  admin-password: "kasm-admin-pass-change-me"
  manager-token: "kasm-manager-token-change-me"
