apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero-manifests
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dwoitzik/homelab-infrastructure.git
    targetRevision: main
    path: kubernetes/system/velero
    directory:
      include: '{secrets,schedule}.yml'
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
