apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: r2-offsite
  namespace: velero
spec:
  provider: aws
  objectStorage:
    bucket: velero-offsite
  config:
    region: auto
    s3ForcePathStyle: "false"
    s3Url: https://61863ddb47e05bc833c7671f69e3454c.r2.cloudflarestorage.com
    checksumAlgorithm: ""
  credential:
    name: velero-r2-credentials
    key: cloud
