apiVersion: v1
kind: Secret
metadata:
  name: velero-s3-credentials
  namespace: velero
type: Opaque
stringData:
  cloud: |
    [default]
    aws_access_key_id = ***REMOVED-GARAGE-S3-ACCESS-KEY***
    aws_secret_access_key = ***REMOVED-GARAGE-S3-SECRET-KEY***
