apiVersion: v1
kind: Secret
metadata:
  name: velero-s3-credentials
  namespace: velero
type: Opaque
stringData:
  cloud: |
    [default]
    aws_access_key_id = GKf5de79528ade5ffced70bd20
    aws_secret_access_key = 1b5bd8fa6bbe0a9a8f360368256b8be9800fcc8b297425caad89c828bf4731a4
