---
- Infrastructure:
    - Proxmox:
        icon: proxmox.png
        href: https://pve.woitzik.dev
        description: Virtualization Platform
    - PBS:
        icon: proxmox.png
        href: https://backup.woitzik.dev
        description: Proxmox Backup Server
    - Router:
        icon: mikrotik.png
        href: https://router.woitzik.dev
        description: MikroTik RB5009
- Cloud Native:
    - ArgoCD:
        icon: argocd.png
        href: https://argo.woitzik.dev
        widget:
          type: argocd
          url: http://argocd-server.argocd.svc.cluster.local
          key: "{{HOMEPAGE_VAR_ARGOCD_TOKEN}}"
    - Longhorn:
        icon: longhorn.png
        href: https://longhorn.woitzik.dev
    - Traefik:
        icon: traefik.png
        href: https://traefik.woitzik.dev
        widget:
          type: traefik
          url: http://10.42.4.18:9000
- Core Apps:
    - Vaultwarden:
        icon: vaultwarden.png
        href: https://vault.woitzik.dev
    - Authelia:
        icon: authelia.png
        href: https://auth.woitzik.dev
    - AdGuard:
        icon: adguard-home.png
        href: https://dns.woitzik.dev
        widget:
          type: adguard
          url: http://10.0.20.2:3001
          username: dw
          password: "{{HOMEPAGE_VAR_ADGUARD_PASSWORD}}"
- Productivity:
    - Paperless:
        icon: paperless.png
        href: https://docs.woitzik.dev
    - Minio:
        icon: minio.png
        href: https://minio.woitzik.dev
    - Open WebUI:
        icon: open-webui.png
        href: https://ai.woitzik.dev
- Monitoring:
    - Grafana:
        icon: grafana.png
        href: https://monitoring.woitzik.dev
        widget:
          type: grafana
          url: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local
          username: admin
          password: "{{HOMEPAGE_VAR_GRAFANA_PASSWORD}}"
    - Uptime Kuma:
        icon: uptime-kuma.png
        href: https://status.woitzik.dev
        widget:
          type: uptimekuma
          url: http://uptime-kuma.monitoring.svc.cluster.local:3001
          slug: default
