---
- title: Infrastructure
  items:
    - Proxmox:
        icon: proxmox.png
        href: https://10.0.10.10:8006
        description: Virtualization Platform
    - PBS:
        icon: proxmox.png
        href: https://10.0.10.110:8007
        description: Proxmox Backup Server
    - Router:
        icon: mikrotik.png
        href: https://router.woitzik.dev
        description: MikroTik RB5009

- title: Cloud Native
  items:
    - ArgoCD:
        icon: argocd.png
        href: https://argo.woitzik.dev
        description: GitOps Controller
        widget:
          type: argocd
          url: https://argo.woitzik.dev
          username: admin
    - Longhorn:
        icon: longhorn.png
        href: https://longhorn.woitzik.dev
        description: Distributed Block Storage
    - Traefik:
        icon: traefik.png
        href: https://traefik.woitzik.dev
        description: Edge Router
        widget:
          type: traefik
          url: https://traefik.woitzik.dev

- title: Core Apps
  items:
    - Vaultwarden:
        icon: vaultwarden.png
        href: https://vault.woitzik.dev
        description: Password Manager
    - Authelia:
        icon: authelia.png
        href: https://auth.woitzik.dev
        description: Identity Provider
    - AdGuard A:
        icon: adguard-home.png
        href: http://10.0.20.2:3001
        description: DNS Filter Node 01
    - AdGuard B:
        icon: adguard-home.png
        href: http://10.0.20.3:3001
        description: DNS Filter Node 02

- title: Productivity
  items:
    - Paperless:
        icon: paperless.png
        href: https://docs.woitzik.dev
        description: Document Management
    - Minio:
        icon: minio.png
        href: https://minio.woitzik.dev
        description: S3 Object Storage
    - Open WebUI:
        icon: open-webui.png
        href: https://ai.woitzik.dev
        description: LLM Interface

- title: Monitoring
  items:
    - Grafana:
        icon: grafana.png
        href: https://monitoring.woitzik.dev
        description: Cluster Metrics
        widget:
          type: grafana
          url: https://monitoring.woitzik.dev
    - Mikrodash:
        icon: mikrotik.png
        href: https://mikrodash.woitzik.dev
        description: Router Dashboard
