apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seafile-shared
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: seafile
  namespace: apps
spec:
  ports:
    - port: 80
      name: http
    - port: 8000
      name: seahub
    - port: 8082
      name: seafile-server
  selector:
    app: seafile
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seafile
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seafile
  template:
    metadata:
      labels:
        app: seafile
    spec:
      containers:
        - name: seafile
          image: seafileltd/seafile-mc:11.0.12
          env:
            - name: DB_HOST
              value: "seafile-mysql"
            - name: DB_ROOT_PASSWD
              valueFrom:
                secretKeyRef:
                  name: seafile-secrets
                  key: mysql-root-password
            - name: SEAFILE_ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: seafile-secrets
                  key: seafile-admin-email
            - name: SEAFILE_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: seafile-secrets
                  key: seafile-admin-password
            - name: SEAFILE_SERVER_HOSTNAME
              value: "seafile.woitzik.dev"
            - name: SEAFILE_SERVER_LETSENCRYPT
              value: "false"
            - name: TIME_ZONE
              value: "Europe/Berlin"
          ports:
            - containerPort: 80
            - containerPort: 8000
            - containerPort: 8082
          volumeMounts:
            - name: shared
              mountPath: /shared
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: seafile-shared
