apiVersion: v1
kind: Secret
metadata:
  name: seafile-secrets
  namespace: apps
type: Opaque
stringData:
  mysql-root-password: "seafile-mysql-root"
  seafile-admin-email: "admin@woitzik.dev"
  seafile-admin-password: "seafile-admin-pass"
  s3-access-key: "GKf5de79528ade5ffced70bd20"
  s3-secret-key: "1b5bd8fa6bbe0a9a8f360368256b8be9800fcc8b297425caad89c828bf4731a4"
