---
- name: Ensure the correct hostname is set
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Update /etc/hosts with the new hostname
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ inventory_hostname }}"
    state: present

- name: Perform system update (apt-get update & upgrade)
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install base packages
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Set timezone to Europe/Berlin
  community.general.timezone:
    name: Europe/Berlin

- name: Install unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present

- name: Install power management tools
  ansible.builtin.apt:
    name:
      - cpufrequtils
      - powertop
    state: present

- name: Set CPU governor to ondemand for power efficiency
  ansible.builtin.copy:
    dest: /etc/default/cpufrequtils
    content: |
      GOVERNOR="ondemand"
    mode: '0644'
  notify: Restart cpufrequtils

- name: Ensure cpufrequtils is enabled and running
  ansible.builtin.systemd:
    name: cpufrequtils
    state: started
    enabled: true
