apiVersion: v1
kind: ServiceAccount
metadata:
  name: keel
  namespace: apps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keel
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keel
subjects:
  - kind: ServiceAccount
    name: keel
    namespace: apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keel
  namespace: apps
  labels:
    app: keel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keel
  template:
    metadata:
      labels:
        app: keel
    spec:
      serviceAccountName: keel
      containers:
        - name: keel
          image: keelhq/keel:0.19.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9300
          env:
            - name: NAMESPACE
              value: "" # Monitor all namespaces
            - name: POLL_INTERVAL
              value: "1h"
            - name: DEBUG
              value: "false"
            - name: NOTIFICATION_LEVEL
              value: "info"
---
apiVersion: v1
kind: Service
metadata:
  name: keel
  namespace: apps
spec:
  ports:
    - port: 9300
      targetPort: 9300
  selector:
    app: keel
