apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-secrets
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: immich-secrets
    creationPolicy: Owner
  data:
    - secretKey: db-password
      remoteRef:
        key: secret/immich
        property: db-password
    - secretKey: jwt-secret
      remoteRef:
        key: secret/immich
        property: jwt-secret
