apiVersion: v1
kind: ConfigMap
metadata:
  name: headscale-config
  namespace: apps
data:
  config.yaml: |
    server_url: https://headscale.woitzik.dev
    listen_addr: 0.0.0.0:8080
    metrics_listen_addr: 0.0.0.0:9090
    grpc_listen_addr: 0.0.0.0:50443
    grpc_allow_insecure: false

    private_key_path: /var/lib/headscale/private.key
    noise:
      private_key_path: /var/lib/headscale/noise_private.key

    db_type: sqlite3
    db_path: /var/lib/headscale/db.sqlite

    derp:
      server:
        enabled: false
      urls:
        - https://controlplane.tailscale.com/derpmap/default
      paths: []
      auto_update_enabled: true
      update_frequency: 24h

    dns_config:
      magic_dns: true
      base_domain: headscale.net
      nameservers:
        - 1.1.1.1
        - 1.0.0.1
      extra_records: []

    oidc:
      issuer: "https://auth.woitzik.dev"
      client_id: "headscale"
      client_secret: "dubist1plebyakalb"
      scope: ["openid", "profile", "email", "groups"]
      strip_email_domain: true

    log:
      format: text
      level: info

    policy_path: /var/lib/headscale/policy.hujson

    ip_prefixes:
      - 100.64.0.0/10
