apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: headscale-oidc
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: headscale-oidc
    creationPolicy: Owner
  data:
    - secretKey: HEADSCALE_OIDC_CLIENT_SECRET
      remoteRef:
        key: secret/headscale
        property: oidc-client-secret
