apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: changedetection
  namespace: changedetection
spec:
  entryPoints: [websecure]
  routes:
    - match: Host(`changedetection.woitzik.dev`)
      kind: Rule
      services: [{name: changedetection, port: 5000}]
      middlewares:
        - name: crowdsec-bouncer
          namespace: apps
        - name: authelia
          namespace: apps
  tls:
    certResolver: default
