---
- name: Update GRUB (reboot required)
  ansible.builtin.command:
    cmd: update-grub
  changed_when: true

- name: Reload systemd and enable pve-cpu-power
  ansible.builtin.systemd:
    name: pve-cpu-power
    daemon_reload: true
    enabled: true
    state: started

- name: Reload udev rules
  ansible.builtin.command:
    cmd: udevadm control --reload-rules
  changed_when: true
