---
- name: Reload monitoring services
  ansible.builtin.uri:
    url: "http://localhost:9090/-/reload"
    method: POST
    status_code: 200
  register: result
  until: result.status is defined and result.status == 200
  retries: 5
  delay: 5
  listen: "Reload monitoring services"

- name: Reload alertmanager
  ansible.builtin.uri:
    url: "http://localhost:9093/-/reload"
    method: POST
    status_code: 200
  register: result
  until: result.status is defined and result.status == 200
  retries: 5
  delay: 5
  listen: "Reload alertmanager"
