---
- name: Reload monitoring services
  ansible.builtin.uri:
    url: http://localhost:9090/-/reload
    method: POST
  register: monitoring_core_result
  until: monitoring_core_result.status == 200
  retries: 5
  delay: 2

- name: Reload alertmanager
  ansible.builtin.uri:
    url: http://localhost:9093/-/reload
    method: POST
  register: monitoring_core_result
  until: monitoring_core_result.status == 200
  retries: 5
  delay: 2
