apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-config
  namespace: apps
data:
  configuration.yml: |
    server:
      address: 'tcp://0.0.0.0:9091/'
    log:
      level: 'debug'

    identity_validation:
      reset_password:
        jwt_secret: '/config/secrets/jwt-secret'

    default_redirection_url: 'https://auth.woitzik.dev'

    authentication_backend:
      file:
        path: '/config/users/users_database.yml'

    session:
      name: 'authelia_session'
      domain: 'woitzik.dev'
      secret: '/config/secrets/session-secret'
      same_site: 'lax'
      expiration: '1h'
      inactivity: '5m'
      remember_me: '1M'
      redis:
        host: 'redis-authelia.database.svc.cluster.local'
        port: 6379
        database_index: 0

    storage:
      encryption_key: '/config/secrets/storage-key'
      postgres:
        address: 'tcp://postgres-authelia.database.svc.cluster.local:5432'
        database: 'authelia'
        username: 'authelia'

    notifier:
      filesystem:
        filename: '/tmp/notification.txt'

    access_control:
      default_policy: 'one_factor'
      rules:
        - domain: 'pve.woitzik.dev'
          policy: 'two_factor'
          subject:
            - 'group:admins'
        - domain: '*.woitzik.dev'
          policy: 'two_factor'
        - domain: 'auth.woitzik.dev'
          policy: 'bypass'

    identity_providers:
      oidc:
        hmac_secret: "***REMOVED-SHARED-OIDC-CLIENT-SECRET***"
        issuer_private_key: |
          ***REMOVED-AUTHELIA-OIDC-PRIVATE-KEY***
        clients:
          - client_id: 'proxmox'
            client_name: 'Proxmox VE'
            client_secret: '$pbkdf2-sha512$310000$Hk4bOREWPhMBgT47B89JeA$VcwSwRAO8un.LVMDsDvOjbd3GVeSgaZwc.2F47MxP6aDoM42ZmTSdgPIBwpEAiH0hvzI2nqKJMcXceAtfQpfXA'
            public: false
            authorization_policy: two_factor
            redirect_uris:
              - 'https://pve.woitzik.dev'
              - 'https://pve.woitzik.dev/api2/extjs/access/oidc/login'
              - 'https://pve.woitzik.dev:8006/api2/extjs/access/oidc/login'
              - 'https://pve.woitzik.dev:443/api2/extjs/access/oidc/login'
            scopes:
              - 'openid'
              - 'profile'
              - 'email'
              - 'groups'
            userinfo_signed_response_alg: 'none'
            consent_mode: implicit
          - client_id: 'pbs'
            client_name: 'Proxmox Backup Server'
            client_secret: '$pbkdf2-sha512$310000$Hk4bOREWPhMBgT47B89JeA$VcwSwRAO8un.LVMDsDvOjbd3GVeSgaZwc.2F47MxP6aDoM42ZmTSdgPIBwpEAiH0hvzI2nqKJMcXceAtfQpfXA'
            public: false
            authorization_policy: two_factor
            redirect_uris:
              - 'https://backup.woitzik.dev'
              - 'https://backup.woitzik.dev/api2/extjs/access/oidc/login'
            scopes:
              - 'openid'
              - 'profile'
              - 'email'
              - 'groups'
            userinfo_signed_response_alg: 'none'
            consent_mode: implicit
          - client_id: 'minio'
            client_name: 'Minio'
            client_secret: '$pbkdf2-sha512$310000$Hk4bOREWPhMBgT47B89JeA$VcwSwRAO8un.LVMDsDvOjbd3GVeSgaZwc.2F47MxP6aDoM42ZmTSdgPIBwpEAiH0hvzI2nqKJMcXceAtfQpfXA'
            public: false
            authorization_policy: two_factor
            redirect_uris:
              - 'https://minio.woitzik.dev'
              - 'https://minio.woitzik.dev/oauth_callback'
            scopes:
              - 'openid'
              - 'profile'
              - 'email'
              - 'groups'
            userinfo_signed_response_alg: 'none'
          - client_id: 'argocd'
            client_name: 'Argo CD'
            client_secret: '$pbkdf2-sha512$310000$Hk4bOREWPhMBgT47B89JeA$VcwSwRAO8un.LVMDsDvOjbd3GVeSgaZwc.2F47MxP6aDoM42ZmTSdgPIBwpEAiH0hvzI2nqKJMcXceAtfQpfXA'
            public: false
            authorization_policy: two_factor
            redirect_uris:
              - 'https://argo.woitzik.dev/auth/callback'
            scopes:
              - 'openid'
              - 'profile'
              - 'email'
              - 'groups'
            userinfo_signed_response_alg: 'none'
