apiVersion: v1
kind: Secret
metadata:
  name: authelia-users-db
  namespace: apps
type: Opaque
data:
  users_database.yml: dXNlcnM6CiAgZGF2aWQ6CiAgICBkaXNwbGF5bmFtZTogIkRhdmlkIgogICAgcGFzc3dvcmQ6ICckYXJnb24yaWQkdj0xOSRtPTY1NTM2LHQ9MyxwPTQkYkUvbG5KMTQrZ3FTdU5ITzJKbk1BdyRCUXByVE5aNXVYbldVNUMmMWVYanJYM3NxNlNKZGw0czN4YTRWQ3Z6RmFrJwogICAgZW1haWw6IGRhdmlkQHdvaXR6aWsuZGV2CiAgICBncm91cHM6CiAgICAgIC0gYWRtaW5zCiAgICAgIC0gZGV2Cg==
