users:
  david:
    displayname: "David"
    password: '$argon2id$v=19$m=65536,t=3,p=4$Zoi8XG3TjDGEzTlgO2DTTQ$iseGveo5ljlhC1JRRr5IgqKbpklslh129bztc+dhSYI'
    email: david@woitzik.dev
    groups:
      - admins
      - dev
