apiVersion: v1
kind: Secret
metadata:
  name: authelia-users-db
  namespace: apps
type: Opaque
data:
  users_database.yml: dXNlcnM6CiAgZGF2aWQ6CiAgICBkaXNwbGF5bmFtZTogIkRhdmlkIgogICAgcGFzc3dvcmQ6ICckYXJnb24yaWQkdj0xOSRtPTY1NTM2LHQ9MyxwPTQkVmhZWkw5anZDVHptWTd0aHByb044dyQ2UXBzOE1QcEtSTTQvQUZ6cXErR1hucnd4YnducmZOV2F4TFNka1hkTG1FJwogICAgZW1haWw6IGRhdmlkQHdvaXR6aWsuZGV2CiAgICBncm91cHM6CiAgICAgIC0gYWRtaW5zCiAgICAgIC0gZGV2Cg==
