users:
  david:
    displayname: "David"
    password: '$argon2id$v=19$m=65536,t=3,p=4$m2xGijvlILqbZH1GPOnLVg$vFAncmgQQPTZMsqRNkWgTKf7IYqTwAikieT9S9P+498'
    email: david@woitzik.dev
    groups:
      - admins
      - dev
