apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/dwoitzik/homelab-infrastructure.git'
        revision: main
        directories:
          - path: kubernetes/apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/dwoitzik/homelab-infrastructure.git'
        targetRevision: main
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: apps
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
