apiVersion: v1
kind: Service
metadata:
  name: redis-authelia
  namespace: database
spec:
  ports:
  - port: 6379
  selector:
    app: redis-authelia
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-authelia
  namespace: database
spec:
  serviceName: "redis-authelia"
  replicas: 1
  selector:
    matchLabels:
      app: redis-authelia
  template:
    metadata:
      labels:
        app: redis-authelia
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: redis
        image: public.ecr.aws/bitnami/redis:7.4
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis-password
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /bitnami/redis/data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 8Gi
