apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: scrutiny-secrets
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: scrutiny-secrets
    creationPolicy: Owner
  data:
    - secretKey: influxdb-password
      remoteRef:
        key: secret/scrutiny
        property: influxdb-password
    - secretKey: influxdb-token
      remoteRef:
        key: secret/scrutiny
        property: influxdb-token
