apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-secrets
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: garage-secrets
    creationPolicy: Owner
  data:
    - secretKey: rpc_secret
      remoteRef:
        key: secret/garage
        property: rpc-secret
    - secretKey: admin_token
      remoteRef:
        key: secret/garage
        property: admin-token
