apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-data
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-meta
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: garage
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garage
  template:
    metadata:
      labels:
        app: garage
    spec:
      containers:
        - name: garage
          image: dxos/garage:0.9.0
          args: ["/garage/garage", "server"]
          env:
            - name: GARAGE_CONFIG
              value: /etc/garage/config.toml
          ports:
            - name: s3
              containerPort: 3900
            - name: rpc
              containerPort: 3901
            - name: admin
              containerPort: 3903
          volumeMounts:
            - name: config
              mountPath: /etc/garage/config.toml
              subPath: config.toml
              readOnly: true
            - name: data
              mountPath: /var/lib/garage/data
            - name: meta
              mountPath: /var/lib/garage/meta
      volumes:
        - name: config
          configMap:
            name: garage-config
        - name: data
          persistentVolumeClaim:
            claimName: garage-data
        - name: meta
          persistentVolumeClaim:
            claimName: garage-meta
---
apiVersion: v1
kind: Service
metadata:
  name: garage
  namespace: apps
spec:
  ports:
    - port: 3900
      targetPort: 3900
      name: s3
    - port: 3903
      targetPort: 3903
      name: admin
  selector:
    app: garage
