apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-secrets
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: paperless-secrets
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: secret/paperless
        property: postgres-password
    - secretKey: ai-api-token
      remoteRef:
        key: secret/paperless
        property: ai-api-token
