apiVersion: v1
kind: Secret
metadata:
  name: paperless-secrets
  namespace: apps
type: Opaque
stringData:
  postgres-password: "TD3fAJ2s1cxJ"
  ai-api-token: "29c9012f7a44bfaf01a197ccb9558eb72ba4838a"
