# --- K3s Kubernetes Cluster (VLAN 20 - srv) ---

resource "proxmox_virtual_environment_vm" "vm_srv_k3s_11_master" {
  vm_id     = 211
  name      = "vm-srv-k3s-11"
  node_name = local.target_node
  tags      = ["k3s", "master", "kubernetes"]
  started   = true
  on_boot   = true

  # Staggered boot (2026-06-20): all 3 k3s VMs starting simultaneously caused a
  # resource storm (load avg 147 within 4 min of boot) that made the Proxmox host
  # unresponsive for several minutes. NFS server boots first (order 1), then
  # k3s nodes 30s apart. See docs/OPERATIONS.md.
  startup {
    order    = 2
    up_delay = 30
  }

  # disk and clone/initialization are creation-time only; ignore prevents Atlantis
  # from stopping the VM (and killing itself) on subsequent plans.
  lifecycle {
    ignore_changes = [clone, initialization, disk]
  }

  clone {
    vm_id = 9000
    full  = true
  }

  agent {
    enabled = true
  }

  # REL-035: units=2048 (default is 1024) gives this VM 2x scheduling
  # priority relative to every LXC on this host when physical CPU is
  # contended. Total allocated vCPU across all VMs/CTs is ~2x the host's 16
  # threads (documented, unavoidable without new hardware -- see
  # docs/AUDIT.md REL-035), so contention *will* happen; this is the sole
  # k3s server (control plane + API server, ADR-015) and the node most of
  # the app workloads schedule onto -- it should win contention over e.g. a
  # Minecraft server or an Ollama inference run.
  cpu {
    cores = 6
    type  = "host"
    units = 2048
  }

  # 2026-08-13 (ADR-015): right-sized down from the etcd-era 28GB
  # dedicated/12GB floating (REL-036) now that this node no longer runs
  # etcd. REL-036's actual trigger was etcd's ReadIndex/apply path starving
  # under kswapd pressure during a single-node cold start with all app
  # workloads concentrated here -- a real incident, but one whose root
  # cause (etcd) ADR-015 removes. Restored to the pre-REL-036 baseline
  # (16GB/8GB) rather than the inflated figure; if a future measured
  # workload profile (Phase 4.7 monitoring) shows this is tight, re-bump
  # with the same evidence bar REL-036 was held to, not preemptively.
  memory {
    dedicated = 16384
    floating  = 8192
  }

  # cache=none + aio=native (O_DIRECT, no QEMU page cache). Originally
  # justified by etcd's fdatasync-vs-QEMU-writeback-cache interaction
  # (REL-012c); kept post-ADR-015 because the same class of risk exists at
  # smaller scale for SQLite's own WAL fsync/checkpoint writes, and because
  # this is now a cheap, no-downside default rather than a load-bearing fix
  # for a specific incident. Underlying storage is local-lvm (LVM-thin),
  # not the old ZFS rpool -- see locals.tf and host-config.tf for the
  # 2026-08-13 ZFS-to-LVM-thin migration this comment used to reference.
  disk {
    datastore_id = local.storage
    interface    = "scsi0"
    size         = 120
    file_format  = "raw"
    cache        = "none"
    aio          = "native"
  }

  network_device {
    bridge  = "vmbr0"
    vlan_id = 20
  }

  # 2026-07-10: root-caused the real source of the "home.lan" DNS
  # search-suffix drift (REL-058/AUTONOMY-STATUS DNS gap) -- it was never
  # RouterOS/DHCP. Live-confirmed on this VM: `networkctl status --json`
  # shows the search domain's ConfigSource as "static", not DHCP; its
  # actual origin is /etc/netplan/50-cloud-init.yaml, generated by
  # Proxmox's own cloud-init writer. When `initialization.dns.domain` is
  # left unset (as it always has been here), Proxmox falls back to the
  # PVE node's own configured search domain (`pvesh get
  # /nodes/pve-mgmt-01/dns` -> search: home.lan) -- confirmed live. The
  # RouterOS `domain = ""` fix in dhcp.tf was correct as written but was
  # never the actual source, which is why its plan always showed zero
  # diff against live router state -- not a provider bug, a wrong
  # hypothesis. `domain = ""` here declares intent explicitly, but note
  # this block is in `lifecycle.ignore_changes` below (same as `disk`),
  # so it has NO effect on this already-provisioned VM -- fixing the live
  # drift needs the PVE node-level default cleared
  # (`pvesh set /nodes/pve-mgmt-01/dns -search ""`, no Terraform resource
  # models this, same class of gap as vzdump.conf/local-pbs's password)
  # plus a cloud-init regen on this VM, both live changes to an
  # etcd-member VM -- proposed, not applied, pending explicit go.
  initialization {
    datastore_id = local.storage
    ip_config {
      ipv4 {
        address = "10.0.20.11/24"
        gateway = "10.0.20.1"
      }
    }
    dns {
      domain  = ""
      servers = ["10.0.20.5"]
    }
    user_account {
      username = "dw"
      keys = [
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJqyhlsY7Ji2Hv3tK1dz0TtAxgVP5quj8UP3JpJnnxL9"
      ]
    }
  }
}

resource "proxmox_virtual_environment_vm" "vm_srv_k3s_12_worker" {
  # 12→8 GB dedicated (REL-036: RAM re-balanced to k3s-11 after single-node
  # reset recovery). Still hosts Traefik, Vault, ArgoCD, CNPG, cert-manager,
  # CrowdSec, Trivy Operator; 8 GB is tight for a cold start but this node
  # only resumes that role once re-joined. Was 8/4 (2026-07) and hit 97%
  # memory during security tooling rollout.
  vm_id     = 212
  name      = "vm-srv-k3s-12"
  node_name = local.target_node
  tags      = ["k3s", "worker", "kubernetes"]
  started   = true
  on_boot   = true

  startup {
    order    = 3
    up_delay = 30
  }

  lifecycle {
    ignore_changes = [clone, initialization, disk]
  }

  clone {
    vm_id = 9000
    full  = true
  }

  agent {
    enabled = true
  }

  # REL-035: see vm-srv-k3s-11 comment -- same priority weighting so this
  # worker's kubelet/containerd don't starve either (etcd runs on k3s-11
  # only, but a starved worker still causes node-not-ready flaps and pod
  # evictions that cascade back onto the control plane).
  cpu {
    cores = 4
    type  = "host"
    units = 2048
  }

  memory {
    dedicated = 8192
    floating  = 4096
  }

  # REL-012c: cache=none + aio=native (see k3s-11 comment).
  # Applied manually via `qm set 212 ...`; disk in ignore_changes.
  disk {
    datastore_id = local.storage
    interface    = "scsi0"
    size         = 120
    file_format  = "raw"
    cache        = "none"
    aio          = "native"
  }

  network_device {
    bridge  = "vmbr0"
    vlan_id = 20
  }

  # 2026-07-10: see vm-srv-k3s-11's comment -- same fix, same ignore_changes
  # caveat (no effect on this already-provisioned VM without a manual
  # cloud-init regen).
  initialization {
    datastore_id = local.storage
    ip_config {
      ipv4 {
        address = "10.0.20.12/24"
        gateway = "10.0.20.1"
      }
    }
    dns {
      domain  = ""
      servers = ["10.0.20.5"]
    }
    user_account {
      username = "dw"
      keys = [
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJqyhlsY7Ji2Hv3tK1dz0TtAxgVP5quj8UP3JpJnnxL9"
      ]
    }
  }
}

resource "proxmox_virtual_environment_vm" "vm_srv_k3s_13_worker" {
  # 2026-08-13 (ADR-014 Option A, reinforced by ADR-015): k3s-13 previously
  # drifted into running as a second etcd member outside of any tracked
  # process (see ADR-014's full incident account -- a 2-member etcd cluster
  # has *less* fault tolerance than 1-member, and directly caused a real
  # outage). It was sized to match k3s-11 (6 cores/12GB) purely because of
  # that etcd role. ADR-015 removes etcd entirely (single-server SQLite) --
  # there is no longer any etcd-member role for k3s-13 to have drifted
  # into, and no reason for it to carry control-plane-grade sizing. Reverted
  # to plain worker sizing matching k3s-12.
  vm_id     = 213
  name      = "vm-srv-k3s-13"
  node_name = local.target_node
  tags      = ["k3s", "worker", "kubernetes"]
  started   = true
  on_boot   = true

  startup {
    order    = 4
    up_delay = 30
  }

  lifecycle {
    ignore_changes = [clone, initialization, disk]
  }

  clone {
    vm_id = 9000
    full  = true
  }

  agent {
    enabled = true
  }

  # REL-035: see vm-srv-k3s-11 comment -- same worker-starvation-avoidance
  # reasoning as k3s-12, not etcd-specific.
  cpu {
    cores = 4
    type  = "host"
    units = 2048
  }

  memory {
    dedicated = 8192
    floating  = 4096
  }

  # cache=none + aio=native (see k3s-11 comment).
  disk {
    datastore_id = local.storage
    interface    = "scsi0"
    size         = 120
    file_format  = "raw"
    cache        = "none"
    aio          = "native"
  }

  network_device {
    bridge  = "vmbr0"
    vlan_id = 20
  }

  # 2026-07-10: see vm-srv-k3s-11's comment -- same fix, same ignore_changes
  # caveat (no effect on this already-provisioned VM without a manual
  # cloud-init regen).
  initialization {
    datastore_id = local.storage
    ip_config {
      ipv4 {
        address = "10.0.20.13/24"
        gateway = "10.0.20.1"
      }
    }
    dns {
      domain  = ""
      servers = ["10.0.20.5"]
    }
    user_account {
      username = "dw"
      keys = [
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJqyhlsY7Ji2Hv3tK1dz0TtAxgVP5quj8UP3JpJnnxL9"
      ]
    }
  }
}
