# --- K3s Kubernetes Cluster (VLAN 20 - srv) ---

resource "proxmox_virtual_environment_vm" "vm_srv_k3s_11_master" {
  vm_id     = 211
  name      = "vm-srv-k3s-11"
  node_name = local.target_node
  tags      = ["k3s", "master", "kubernetes"]
  started   = true
  on_boot   = true

  # Staggered boot (2026-06-20): all 3 k3s VMs starting simultaneously caused a
  # resource storm (load avg 147 within 4 min of boot) that made the Proxmox host
  # unresponsive for several minutes. NFS server boots first (order 1), then
  # k3s nodes 30s apart. See docs/OPERATIONS.md.
  startup {
    order    = 2
    up_delay = 30
  }

  # disk and clone/initialization are creation-time only; ignore prevents Atlantis
  # from stopping the VM (and killing itself) on subsequent plans.
  lifecycle {
    ignore_changes = [clone, initialization, disk]
  }

  clone {
    vm_id = 9000
    full  = true
  }

  agent {
    enabled = true
  }

  # REL-035: units=2048 (default is 1024) gives these VMs 2x scheduling
  # priority relative to every LXC on this host when physical CPU is
  # contended. Total allocated vCPU across all VMs/CTs is ~2x the host's 16
  # threads (documented, unavoidable without new hardware -- see
  # docs/AUDIT.md REL-035), so contention *will* happen; without a priority
  # weight, etcd's fdatasync calls compete on equal footing with e.g. a
  # Minecraft server or an Ollama inference run and lose, causing the
  # repeated REL-012c-style crash loops. This VM runs etcd -- it must win
  # that contention every time.
  cpu {
    cores = 6
    type  = "host"
    units = 2048
  }

  memory {
    dedicated = 16384
    floating  = 8192
  }

  # REL-012c: cache=none + aio=native (O_DIRECT, no QEMU page cache).
  # With cache=writeback, large sequential writes (container image pulls) accumulate
  # in the QEMU page cache; when etcd later calls fdatasync on the WAL, QEMU must
  # flush ALL dirty pages to ZFS at once → 8–127s stalls → etcd lease timeout →
  # k3s crash loop. cache=none eliminates this: every VM write goes directly to
  # ZFS ARC in small increments, so fdatasync sees only etcd's own dirty data.
  # ZFS tuning (/etc/modprobe.d/zfs.conf): zfs_dirty_data_max=256MB,
  # zfs_txg_timeout=5s, zfs_arc_max=16GB bounds each txg commit to SLC capacity.
  # Applied manually via `qm set 211 ...`; disk is in ignore_changes so
  # Atlantis will not re-apply this block after initial VM creation.
  # REL-012d (2026-08-01): 4→6 cores + 12→16GB dedicated. This node runs etcd +
  # control plane + the bulk of app workloads. Cold start of ~60 pods (all at
  # once after a host reboot, e.g. post-vacation power-on) starved etcd's
  # ReadIndex/apply path on 4 cores → "apply request took too long" →
  # leaderelection lost → k3s systemd restart loop (NRestarts=50 in 10h). 6
  # cores leaves headroom for the boot storm; also see the k3s.service.d
  # 30-restart-backoff.conf drop-in (RestartSec=90s) applied on 2026-08-01.
  # REL-035 (2x vCPU oversubscription on this host) is unchanged -- this bumps
  # one etcd node, not total allocation.
  disk {
    datastore_id = local.storage
    interface    = "scsi0"
    size         = 120
    file_format  = "raw"
    cache        = "none"
    aio          = "native"
  }

  network_device {
    bridge  = "vmbr0"
    vlan_id = 20
  }

  # 2026-07-10: root-caused the real source of the "home.lan" DNS
  # search-suffix drift (REL-058/AUTONOMY-STATUS DNS gap) -- it was never
  # RouterOS/DHCP. Live-confirmed on this VM: `networkctl status --json`
  # shows the search domain's ConfigSource as "static", not DHCP; its
  # actual origin is /etc/netplan/50-cloud-init.yaml, generated by
  # Proxmox's own cloud-init writer. When `initialization.dns.domain` is
  # left unset (as it always has been here), Proxmox falls back to the
  # PVE node's own configured search domain (`pvesh get
  # /nodes/pve-mgmt-01/dns` -> search: home.lan) -- confirmed live. The
  # RouterOS `domain = ""` fix in dhcp.tf was correct as written but was
  # never the actual source, which is why its plan always showed zero
  # diff against live router state -- not a provider bug, a wrong
  # hypothesis. `domain = ""` here declares intent explicitly, but note
  # this block is in `lifecycle.ignore_changes` below (same as `disk`),
  # so it has NO effect on this already-provisioned VM -- fixing the live
  # drift needs the PVE node-level default cleared
  # (`pvesh set /nodes/pve-mgmt-01/dns -search ""`, no Terraform resource
  # models this, same class of gap as vzdump.conf/local-pbs's password)
  # plus a cloud-init regen on this VM, both live changes to an
  # etcd-member VM -- proposed, not applied, pending explicit go.
  initialization {
    datastore_id = local.storage
    ip_config {
      ipv4 {
        address = "10.0.20.11/24"
        gateway = "10.0.20.1"
      }
    }
    dns {
      domain  = ""
      servers = ["10.0.20.5"]
    }
    user_account {
      username = "dw"
      keys = [
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJqyhlsY7Ji2Hv3tK1dz0TtAxgVP5quj8UP3JpJnnxL9"
      ]
    }
  }
}

resource "proxmox_virtual_environment_vm" "vm_srv_k3s_12_worker" {
  # 12 GB dedicated + 8 GB floating — hosts Traefik, Vault, ArgoCD, CNPG,
  # cert-manager, CrowdSec, Trivy Operator. Was 8/4 but hit 97% memory
  # causing API server OOM crashes during security tooling rollout.
  vm_id     = 212
  name      = "vm-srv-k3s-12"
  node_name = local.target_node
  tags      = ["k3s", "worker", "kubernetes"]
  started   = true
  on_boot   = true

  startup {
    order    = 3
    up_delay = 30
  }

  lifecycle {
    ignore_changes = [clone, initialization, disk]
  }

  clone {
    vm_id = 9000
    full  = true
  }

  agent {
    enabled = true
  }

  # REL-035: see vm-srv-k3s-11 comment -- same priority weighting so this
  # worker's kubelet/containerd don't starve either (etcd runs on k3s-11
  # only, but a starved worker still causes node-not-ready flaps and pod
  # evictions that cascade back onto the control plane).
  cpu {
    cores = 4
    type  = "host"
    units = 2048
  }

  memory {
    dedicated = 12288
    floating  = 8192
  }

  # REL-012c: cache=none + aio=native (see k3s-11 comment).
  # Applied manually via `qm set 212 ...`; disk in ignore_changes.
  disk {
    datastore_id = local.storage
    interface    = "scsi0"
    size         = 120
    file_format  = "raw"
    cache        = "none"
    aio          = "native"
  }

  network_device {
    bridge  = "vmbr0"
    vlan_id = 20
  }

  # 2026-07-10: see vm-srv-k3s-11's comment -- same fix, same ignore_changes
  # caveat (no effect on this already-provisioned VM without a manual
  # cloud-init regen).
  initialization {
    datastore_id = local.storage
    ip_config {
      ipv4 {
        address = "10.0.20.12/24"
        gateway = "10.0.20.1"
      }
    }
    dns {
      domain  = ""
      servers = ["10.0.20.5"]
    }
    user_account {
      username = "dw"
      keys = [
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJqyhlsY7Ji2Hv3tK1dz0TtAxgVP5quj8UP3JpJnnxL9"
      ]
    }
  }
}

resource "proxmox_virtual_environment_vm" "vm_srv_k3s_13_worker" {
  # REL-012d: k3s-13 is a control-plane + etcd member (NOT a pure agent),
  # but was sized at 4 cores / 8 GB while k3s-11 got 6 cores / 16 GB.
  # Under cold-start + regular load it exhausts CPU/RAM → etcd apply/ReadIndex
  # stalls → k3s-11 loses Raft quorum → control-plane crash loop. Matched to
  # k3s-11 (6 cores, 12 GB dedicated + 4 GB floating) so both etcd members
  # have equal headroom. Host has 64 GB DDR4; overcommit gate still passes
  # (dedicated sum 36→40 GB, ceiling 50 GB).
  vm_id     = 213
  name      = "vm-srv-k3s-13"
  node_name = local.target_node
  tags      = ["k3s", "worker", "kubernetes"]
  started   = true
  on_boot   = true

  startup {
    order    = 4
    up_delay = 30
  }

  lifecycle {
    ignore_changes = [clone, initialization, disk]
  }

  clone {
    vm_id = 9000
    full  = true
  }

  agent {
    enabled = true
  }

  # REL-035: see vm-srv-k3s-11 comment.
  cpu {
    cores = 6
    type  = "host"
    units = 2048
  }

  memory {
    dedicated = 12288
    floating  = 4096
  }

  # REL-012c: cache=none + aio=native (see k3s-11 comment).
  # Applied manually via `qm set 213 ...`; disk in ignore_changes.
  disk {
    datastore_id = local.storage
    interface    = "scsi0"
    size         = 120
    file_format  = "raw"
    cache        = "none"
    aio          = "native"
  }

  network_device {
    bridge  = "vmbr0"
    vlan_id = 20
  }

  # 2026-07-10: see vm-srv-k3s-11's comment -- same fix, same ignore_changes
  # caveat (no effect on this already-provisioned VM without a manual
  # cloud-init regen).
  initialization {
    datastore_id = local.storage
    ip_config {
      ipv4 {
        address = "10.0.20.13/24"
        gateway = "10.0.20.1"
      }
    }
    dns {
      domain  = ""
      servers = ["10.0.20.5"]
    }
    user_account {
      username = "dw"
      keys = [
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJqyhlsY7Ji2Hv3tK1dz0TtAxgVP5quj8UP3JpJnnxL9"
      ]
    }
  }
}
