apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - "--no-autoupdate"
        - run
        - "--token"
        - "5JsuCGmNEvAJnOCVDnhofsPJvB7LzH1XmS2MFjFP"
