apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-secrets
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: cloudflared-secrets
    creationPolicy: Owner
  data:
    - secretKey: tunnel-token
      remoteRef:
        key: secret/cloudflared
        property: tunnel-token
