apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secrets
  namespace: apps
type: Opaque
stringData:
  tunnel-token: "eyJhIjoiNjE4NjNkZGI0N2UwNWJjODMzYzc2NzFmNjllMzQ1NGMiLCJ0IjoiMWYyZTBmNzgtMjE0Yi00ZjU5LTg4MWQtMzdlMjI2MjVhZTZlIiwicyI6IlpUY3dNR1JoTURZdE5tUXlPQzAwT0RNekxUazFOR0V0Tm1ZeE5ETTNOVFk0WVRRMk56Z3pZVEkxTWpBdE5qWmxaaTAwWldZNExUaGtabVl0T0dVM056WTRNemN5TW1RMCJ9"
