[rpi_nodes]
rpi-srv-01 ansible_host=10.0.20.2
rpi-srv-02 ansible_host=10.0.20.3

[app_nodes]
ct-srv-docker-01 ansible_host=10.0.20.252 ansible_user=root

[nodes:children]
rpi_nodes
app_nodes

[rpi_nodes:vars]
ansible_user=dw
ansible_ssh_private_key_file=~/.ssh/homelab-infrastructure
