[rpi_nodes]
rpi-srv-01 ansible_host=10.0.20.2
rpi-srv-02 ansible_host=10.0.20.3

[app_nodes]
ct-srv-docker-01 ansible_host=10.0.20.252

[mgmt_nodes]
ct-mgmt-pbs-01 ansible_host=10.0.10.110

[dmz_proxies]
ct-dmz-proxy-01 ansible_host=10.0.30.2

[dmz_games]
ct-dmz-games-01 ansible_host=10.0.30.3

[ai_nodes]
ct-srv-ai-01 ansible_host=10.0.20.251

# --- Group Hierarchies ---

[dmz_nodes:children]
dmz_proxies
dmz_games

[nodes:children]
rpi_nodes
app_nodes
dmz_nodes
