---
- name: Provision Base OS and Docker
  hosts: nodes
  become: yes
  vars_files:
    - vars/secrets.yml
  roles:
    - common
    - docker
    - watchtower
    - monitoring_agent

- name: Provision HA Core Services
  hosts: rpi_nodes
  become: yes
  vars_files:
    - vars/secrets.yml
  roles:
    - keepalived
    - adguard
    - unbound
    - nginx-proxy-manager

- name: Provision Application Services
  hosts: app_nodes
  become: yes
  vars_files:
    - vars/secrets.yml
  roles:
    - vaultwarden
    - mikrodash
    - monitoring_core
