apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: synapse-secrets
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: synapse-secrets
    creationPolicy: Owner
  data:
    - remoteRef:
        key: secret/synapse
        property: db-password
      secretKey: SYNAPSE_DB_PASSWORD
