apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 27.0.2
    chart: traefik
    helm:
      values: |
        serversTransport:
          insecureSkipVerify: true
        ports:
          web:
            redirectTo:
              port: websecure
          websecure:
            tls:
              enabled: true
        logs:
          general:
            level: DEBUG
          access:
            enabled: true
        ingressRoute:
          dashboard:
            enabled: false
        tlsStore:
          default:
            defaultCertificate:
              secretName: wildcard-woitzik-dev-tls
        tolerations:
        - key: "storage"
          operator: "Equal"
          value: "sdcard"
          effect: "NoSchedule"
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                - key: node-type
                  operator: In
                  values:
                  - rpi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
