apiVersion: v1
kind: Service
metadata:
  name: external-router
  namespace: apps
spec:
  ports:
  - port: 443
    targetPort: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-router
  namespace: apps
subsets:
- addresses:
  - ip: 10.0.10.1
  ports:
  - port: 443
---
apiVersion: v1
kind: Service
metadata:
  name: external-pve
  namespace: apps
spec:
  ports:
  - port: 8006
    targetPort: 8006
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-pve
  namespace: apps
subsets:
- addresses:
  - ip: 10.0.10.10
  ports:
  - port: 8006
---
apiVersion: v1
kind: Service
metadata:
  name: external-pbs
  namespace: apps
spec:
  ports:
  - port: 8007
    targetPort: 8007
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-pbs
  namespace: apps
subsets:
- addresses:
  - ip: 10.0.10.110
  ports:
  - port: 8007
---
apiVersion: v1
kind: Service
metadata:
  name: external-dns
  namespace: apps
spec:
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-dns
  namespace: apps
subsets:
- addresses:
  - ip: 10.0.20.2
  ports:
  - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: infrastructure-https-ingress
  namespace: apps
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: apps-authelia@kubernetescrd
    traefik.ingress.kubernetes.io/service.serversscheme: https
spec:
  rules:
  - host: router.woitzik.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: external-router
            port:
              number: 443
  - host: pve.woitzik.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: external-pve
            port:
              number: 8006
  - host: backup.woitzik.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: external-pbs
            port:
              number: 8007
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: infrastructure-http-ingress
  namespace: apps
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: apps-authelia@kubernetescrd
spec:
  rules:
  - host: dns.woitzik.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: external-dns
            port:
              number: 80
