apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: insecure-transport
  namespace: apps
spec:
  insecureSkipVerify: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: infrastructure-https-ingress
  namespace: apps
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: apps-authelia@kubernetescrd
    traefik.ingress.kubernetes.io/service.serversscheme: https
    traefik.ingress.kubernetes.io/service.serverstransport: apps-insecure-transport@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: router.woitzik.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: external-router
            port:
              number: 443
  - host: pve.woitzik.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: external-pve
            port:
              number: 8006
  - host: backup.woitzik.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: external-pbs
            port:
              number: 8007
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: infrastructure-http-ingress
  namespace: apps
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: apps-authelia@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: dns.woitzik.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: external-dns
            port:
              number: 3001
