apiVersion: v1
kind: Secret
metadata:
  name: gitea-secrets
  namespace: apps
type: Opaque
stringData:
  admin-password: REPLACE_WITH_ADMIN_PASSWORD
  secret-key: REPLACE_WITH_SECRET_KEY
  internal-token: REPLACE_WITH_INTERNAL_TOKEN
