apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos-mesh
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.chaos-mesh.org
    targetRevision: 2.8.3
    chart: chaos-mesh
    helm:
      values: |
        controllerManager:
          replicaCount: 1
        chaosDaemon:
          runtime: containerd
          socketPath: /run/k3s/containerd/containerd.sock
        dashboard:
          create: true
          securityMode: false
  destination:
    server: https://kubernetes.default.svc
    namespace: chaos-mesh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
