---
- name: Create Minio directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: '1000'
    group: '1000'
    mode: '0755'
  loop:
    - /opt/minio
    - /opt/minio/data

- name: Deploy Minio docker-compose template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/minio/docker-compose.yml
    mode: '0644'

- name: Start Minio container via docker compose
  ansible.builtin.command: docker compose up -d
  args:
    chdir: /opt/minio
  register: minio_compose_output
  changed_when: minio_compose_output.stdout != ""
