---
- name: Create Minio directories
  file:
    path: "{{ item }}"
    state: directory
    owner: 1000
    group: 1000
  loop:
    - /opt/minio
    - /opt/minio/data

- name: Deploy Minio docker-compose template
  template:
    src: docker-compose.yml.j2
    dest: /opt/minio/docker-compose.yml
    mode: '0644'

- name: Start Minio container via docker compose
  command: docker compose up -d
  args:
    chdir: /opt/minio
