---
- name: Create Watchtower directory
  ansible.builtin.file:
    path: /opt/watchtower
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Deploy Watchtower Docker Compose
  ansible.builtin.copy:
    dest: /opt/watchtower/docker-compose.yml
    content: |
      services:
        watchtower:
          image: containrrr/watchtower@sha256:6dd50763bbd632a83cb154d5451700530d1e44200b268a4e9488fefdfcf2b038
          container_name: watchtower
          restart: unless-stopped
          mem_limit: 128m
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
          environment:
            - WATCHTOWER_CLEANUP=true
            - WATCHTOWER_POLL_INTERVAL=86400
            - DOCKER_API_VERSION=1.40
    mode: '0644'

- name: Start Watchtower
  community.docker.docker_compose_v2:
    project_src: /opt/watchtower
    state: present
